require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TransportersController do

  # This should return the minimal set of attributes required to create a valid
  # Transporter. As you add validations to Transporter, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TransportersController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all transporters as @transporters" do
      transporter = Transporter.create! valid_attributes
      get :index, {}, valid_session
      assigns(:transporters).should eq([transporter])
    end
  end

  describe "GET show" do
    it "assigns the requested transporter as @transporter" do
      transporter = Transporter.create! valid_attributes
      get :show, {:id => transporter.to_param}, valid_session
      assigns(:transporter).should eq(transporter)
    end
  end

  describe "GET new" do
    it "assigns a new transporter as @transporter" do
      get :new, {}, valid_session
      assigns(:transporter).should be_a_new(Transporter)
    end
  end

  describe "GET edit" do
    it "assigns the requested transporter as @transporter" do
      transporter = Transporter.create! valid_attributes
      get :edit, {:id => transporter.to_param}, valid_session
      assigns(:transporter).should eq(transporter)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Transporter" do
        expect {
          post :create, {:transporter => valid_attributes}, valid_session
        }.to change(Transporter, :count).by(1)
      end

      it "assigns a newly created transporter as @transporter" do
        post :create, {:transporter => valid_attributes}, valid_session
        assigns(:transporter).should be_a(Transporter)
        assigns(:transporter).should be_persisted
      end

      it "redirects to the created transporter" do
        post :create, {:transporter => valid_attributes}, valid_session
        response.should redirect_to(Transporter.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved transporter as @transporter" do
        # Trigger the behavior that occurs when invalid params are submitted
        Transporter.any_instance.stub(:save).and_return(false)
        post :create, {:transporter => {}}, valid_session
        assigns(:transporter).should be_a_new(Transporter)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Transporter.any_instance.stub(:save).and_return(false)
        post :create, {:transporter => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested transporter" do
        transporter = Transporter.create! valid_attributes
        # Assuming there are no other transporters in the database, this
        # specifies that the Transporter created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Transporter.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => transporter.to_param, :transporter => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested transporter as @transporter" do
        transporter = Transporter.create! valid_attributes
        put :update, {:id => transporter.to_param, :transporter => valid_attributes}, valid_session
        assigns(:transporter).should eq(transporter)
      end

      it "redirects to the transporter" do
        transporter = Transporter.create! valid_attributes
        put :update, {:id => transporter.to_param, :transporter => valid_attributes}, valid_session
        response.should redirect_to(transporter)
      end
    end

    describe "with invalid params" do
      it "assigns the transporter as @transporter" do
        transporter = Transporter.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Transporter.any_instance.stub(:save).and_return(false)
        put :update, {:id => transporter.to_param, :transporter => {}}, valid_session
        assigns(:transporter).should eq(transporter)
      end

      it "re-renders the 'edit' template" do
        transporter = Transporter.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Transporter.any_instance.stub(:save).and_return(false)
        put :update, {:id => transporter.to_param, :transporter => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested transporter" do
      transporter = Transporter.create! valid_attributes
      expect {
        delete :destroy, {:id => transporter.to_param}, valid_session
      }.to change(Transporter, :count).by(-1)
    end

    it "redirects to the transporters list" do
      transporter = Transporter.create! valid_attributes
      delete :destroy, {:id => transporter.to_param}, valid_session
      response.should redirect_to(transporters_url)
    end
  end

end
